[2025-05-15T09:41:06.240+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_sales_csv.load_csv scheduled__2023-01-30T00:00:00+00:00 [queued]>
[2025-05-15T09:41:06.307+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_sales_csv.load_csv scheduled__2023-01-30T00:00:00+00:00 [queued]>
[2025-05-15T09:41:06.310+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T09:41:06.313+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T09:41:06.320+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T09:41:06.446+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_csv> on 2023-01-30 00:00:00+00:00
[2025-05-15T09:41:06.508+0000] {standard_task_runner.py:55} INFO - Started process 412 to run task
[2025-05-15T09:41:06.512+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_sales_csv', 'load_csv', 'scheduled__2023-01-30T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/load_sales.py', '--cfg-path', '/tmp/tmp6h8vqezs']
[2025-05-15T09:41:06.520+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask load_csv
[2025-05-15T09:41:06.818+0000] {task_command.py:389} INFO - Running <TaskInstance: load_sales_csv.load_csv scheduled__2023-01-30T00:00:00+00:00 [running]> on host 1430ca430efd
[2025-05-15T09:41:08.696+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_sales_csv
AIRFLOW_CTX_TASK_ID=load_csv
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-30T00:00:00+00:00
[2025-05-15T09:42:13.236+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1881, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 988, in do_executemany
    **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedTable: relation "raw_sales" does not exist
LINE 1: INSERT INTO raw_sales ("InvoiceNo", "StockCode", "Descriptio...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_sales.py", line 10, in load_csv_to_postgres
    df.to_sql('raw_sales', engine, if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1770, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1350, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1340, in insert_records
    table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 967, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 882, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 335, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1881, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 988, in do_executemany
    **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "raw_sales" does not exist
LINE 1: INSERT INTO raw_sales ("InvoiceNo", "StockCode", "Descriptio...
                    ^

[SQL: INSERT INTO raw_sales ("InvoiceNo", "StockCode", "Description", "Quantity", "InvoiceDate", "UnitPrice", "CustomerID", "Country") VALUES (%(InvoiceNo)s, %(StockCode)s, %(Description)s, %(Quantity)s, %(InvoiceDate)s, %(UnitPrice)s, %(CustomerID)s, %(Country)s)]
[parameters: ({'InvoiceNo': '536365', 'StockCode': '85123A', 'Description': 'WHITE HANGING HEART T-LIGHT HOLDER', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 2.55, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '71053', 'Description': 'WHITE METAL LANTERN', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 3.39, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '84406B', 'Description': 'CREAM CUPID HEARTS COAT HANGER', 'Quantity': 8, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 2.75, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '84029G', 'Description': 'KNITTED UNION FLAG HOT WATER BOTTLE', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 3.39, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '84029E', 'Description': 'RED WOOLLY HOTTIE WHITE HEART.', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 3.39, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '22752', 'Description': 'SET 7 BABUSHKA NESTING BOXES', 'Quantity': 2, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 7.65, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '21730', 'Description': 'GLASS STAR FROSTED T-LIGHT HOLDER', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 4.25, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536366', 'StockCode': '22633', 'Description': 'HAND WARMER UNION JACK', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:28:00', 'UnitPrice': 1.85, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}  ... displaying 10 of 541909 total bound parameter sets ...  {'InvoiceNo': '581587', 'StockCode': '23255', 'Description': 'CHILDRENS CUTLERY CIRCUS PARADE', 'Quantity': 4, 'InvoiceDate': '2011-12-09 12:50:00', 'UnitPrice': 4.15, 'CustomerID': 12680.0, 'Country': 'France'}, {'InvoiceNo': '581587', 'StockCode': '22138', 'Description': 'BAKING SET 9 PIECE RETROSPOT ', 'Quantity': 3, 'InvoiceDate': '2011-12-09 12:50:00', 'UnitPrice': 4.95, 'CustomerID': 12680.0, 'Country': 'France'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-05-15T09:42:13.541+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=load_sales_csv, task_id=load_csv, execution_date=20230130T000000, start_date=20250515T094106, end_date=20250515T094213
[2025-05-15T09:42:13.716+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task load_csv ((psycopg2.errors.UndefinedTable) relation "raw_sales" does not exist
LINE 1: INSERT INTO raw_sales ("InvoiceNo", "StockCode", "Descriptio...
                    ^

[SQL: INSERT INTO raw_sales ("InvoiceNo", "StockCode", "Description", "Quantity", "InvoiceDate", "UnitPrice", "CustomerID", "Country") VALUES (%(InvoiceNo)s, %(StockCode)s, %(Description)s, %(Quantity)s, %(InvoiceDate)s, %(UnitPrice)s, %(CustomerID)s, %(Country)s)]
[parameters: ({'InvoiceNo': '536365', 'StockCode': '85123A', 'Description': 'WHITE HANGING HEART T-LIGHT HOLDER', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 2.55, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '71053', 'Description': 'WHITE METAL LANTERN', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 3.39, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '84406B', 'Description': 'CREAM CUPID HEARTS COAT HANGER', 'Quantity': 8, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 2.75, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '84029G', 'Description': 'KNITTED UNION FLAG HOT WATER BOTTLE', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 3.39, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '84029E', 'Description': 'RED WOOLLY HOTTIE WHITE HEART.', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 3.39, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '22752', 'Description': 'SET 7 BABUSHKA NESTING BOXES', 'Quantity': 2, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 7.65, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536365', 'StockCode': '21730', 'Description': 'GLASS STAR FROSTED T-LIGHT HOLDER', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:26:00', 'UnitPrice': 4.25, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}, {'InvoiceNo': '536366', 'StockCode': '22633', 'Description': 'HAND WARMER UNION JACK', 'Quantity': 6, 'InvoiceDate': '2010-12-01 08:28:00', 'UnitPrice': 1.85, 'CustomerID': 17850.0, 'Country': 'United Kingdom'}  ... displaying 10 of 541909 total bound parameter sets ...  {'InvoiceNo': '581587', 'StockCode': '23255', 'Description': 'CHILDRENS CUTLERY CIRCUS PARADE', 'Quantity': 4, 'InvoiceDate': '2011-12-09 12:50:00', 'UnitPrice': 4.15, 'CustomerID': 12680.0, 'Country': 'France'}, {'InvoiceNo': '581587', 'StockCode': '22138', 'Description': 'BAKING SET 9 PIECE RETROSPOT ', 'Quantity': 3, 'InvoiceDate': '2011-12-09 12:50:00', 'UnitPrice': 4.95, 'CustomerID': 12680.0, 'Country': 'France'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 412)
[2025-05-15T09:42:14.523+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T09:42:14.884+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
